### ISSUE TITLE
Checkbox Field Amount is not showing in Cart Page

### ISSUE THREAD

**Issue by RohanSharma2598** [Codeinwp/woocommerce-product-addon#155] opened 2023-06-19 11:25 UTC
### Description

This is the issue I am facing with the Checkbox PPOM Field. I have created this field and placed option to add a fix amount of $5, $10, and $15 dollars to the product.

Everything looks fine on the product page and when I select the checkbox, the amount associated to that checkbox gets added to the amount of the product.

The problem happens when I add that product to the cart and check the cart page, I cannot see the checkbox amount being added there.

### Step-by-step reproduction instructions

1. Go to your WordPress Dashboard > Woocommerce > PPOM Fields and add a Checkbox field in the Field Group
2. Add options in the field group to add different amounts to the product.
3. Assign this field group to the products you want.
4. Go to the product where you assigned the field group and tick the checkbox to add the fix amount to the total amount of the product.
5. Add the product to the cart.
6. Check the cart page and you will not see the checkbox amount being added to the product amount.

### Screenshots, screen recording, code snippet or Help Scout ticket

Screen recording: https://share.getcloudapp.com/Jruebbzp
Help Scout: https://secure.helpscout.net/conversation/2265569983/372249?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment] 2023-11-16 09:07
Hey @RohanSharma2598,

I checked with the `development` branch, and it seems working fine from my end.
Ref: https://tinyurl.com/yojwtxl4

@irinelenache If possible, could you also check on your end?

Thanks

**Comment by irinelenache** [comment] 2023-11-16 15:38
@RohanSharma2598 @girishpanchal30 I see the issue is happening because the **Fixed fee** option was enabled in the field options. With the option disabled, the price is fine on the cart page

**Comment by girishpanchal30** [comment] 2023-11-21 11:29
@irinelenache I've reviewed the issue with a fixed fee and fixed it with this PR - https://github.com/Codeinwp/woocommerce-product-addon/pull/188

**Comment by irinelenache** [comment] 2023-11-22 08:03
@RohanSharma2598 @girishpanchal30 Tested and the issue is fixed now, thank you 🚀

**Closed** 2024-02-28 17:57 UTC
Labels: bug, released, customer report
