### ISSUE TITLE
Layout conflict with PPOM on product page on the quantity field and add to cart

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/woocommerce-product-addon#106] opened 2022-08-16 09:32 UTC
### Description:

When the PPOM plugin is active, if you add its field to the product page, the layout of the quantity field and add to cart button changes.

### How to reproduce:

1. Make sure to have Neve and the free version of PPOM installed.
2. Navigate to PPOM settings to attach some fields to a product.
![Markup on 2022-08-16 at 12:29:50](https://user-images.githubusercontent.com/26867648/184847206-a4eacfd7-abcf-407a-a684-1b06e6aff34e.png)

3. Just choose a product and use the default fields available there.

![Markup on 2022-08-16 at 12:31:21](https://user-images.githubusercontent.com/26867648/184847253-735c1755-f483-464a-96af-62d0f9f79acb.png)

4. Check the product page, and then check it again without the PPOM plugin active. 

### Expected behaviour:

![Markup on 2022-08-16 at 12:31:44](https://user-images.githubusercontent.com/26867648/184847159-70d308df-4025-4722-9d0e-0be190618228.png)

### Current behaviour:

![Markup on 2022-08-16 at 12:30:58](https://user-images.githubusercontent.com/26867648/184847171-8f0c51cc-4567-405c-9b7e-2667a42cb13c.png)

### Technical info
* WordPress version: 6.0.1
* Theme version: 3.3.5
* PPOM version: 30.1.2
* WooCommerce version: 6.8.0

**Comment by mskapusuz** [comment] 2023-02-26 22:16
I investigated that issue together with some different themes but couldn't find the logic behind the JS implementation, which forces disabling `display:flex`.

I think there are two possible ways to handle it:
1. Having a WP filter to manage the override in PPOM. Also in Neve, suppress the PPOM override on the `form.cart` by an `add_filter` call. In this way, only Neve users potentially will be affected.
2. Completely remove the JS logic which forces disabling `display:flex` on the PPOM

**Comment by mskapusuz** [comment] 2023-03-03 00:24
That issue was transferred from https://github.com/Codeinwp/neve/issues/3573

**Comment by mskapusuz** [comment] 2023-03-03 01:09
Note: currently Github Actions doesn't work properly https://www.githubstatus.com/incidents/qfby3shb6r3w

I'll ask QA test for this issue once GH Action checks are passed.

**Comment by irinelenache** [comment] 2023-03-03 11:26
@mskapusuz Tested and the issue is fixed, didn't find any other problem 🚀

**Comment by mskapusuz** [comment] 2023-03-31 15:14
I'll closed that PR once https://github.com/Codeinwp/neve/pull/3866 released too

**Closed** 2023-04-11 19:12 UTC
Labels: help wanted, released, small
