### ISSUE TITLE
Date field looses its value if mandatory fields aren't complete and product is added to the cart

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/woocommerce-product-addon#154] opened 2023-06-14 07:46 UTC
### Description

On a product with four mandatory fields, I also used a Date input, and if a required field is left uncomplete and the product is added to the cart, the Date input looses its value

### Step-by-step reproduction instructions

1. Create a new group with three fields: Date input, text, text
2. Make all of them required
3. Navigate to the product page where these are displayed and choose a date, and fill in only one text
4. Add the product to the cart -> it will fail as all the fields were mandatory
5. The Date input lost its value

### Screenshots, screen recording, code snippet or Help Scout ticket

![before-adding-to-the-cart](https://github.com/Codeinwp/woocommerce-product-addon/assets/26867648/a914e400-75df-4db6-90ee-368f684e34df)

![after-adding-to-cart](https://github.com/Codeinwp/woocommerce-product-addon/assets/26867648/51b8d312-31fd-4f49-ae3d-a7c6a9ed6f3d)

Reported here: https://wordpress.org/support/topic/losing-field-values-on-missing-required-field/

### Environment info

https://pastebin.com/ETfTVyLY

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment] 2023-11-27 10:26
@stefan-cotitosu @girishpanchal30 Tested and the issue is fixed now 👍

**Closed** 2024-02-28 17:55 UTC
Labels: bug, released
