### ISSUE TITLE
Field Popup edit in Cart doesn't display updated value

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#222] opened 2023-12-22 18:13 UTC
### Description

A user reported that when changing the product attributes in the Field Popup on the cart page, the value displayed in the input box doesn't change.

ref: https://secure.helpscout.net/conversation/2460322805/397708?viewId=212385

### Step-by-step reproduction instructions

1. Go to WooCommerce > Settings > PPOM Settings
2. Click Addons > Cart Edit
3. Enable PPOM Cart Edit
4. Enable Popup Edit
5. Save the settings and go to the shop page
6. Add a PPOM product to the cart
7. Open the cart page and click on the Field Popup button
8. Type in a new value and click on Update
9. Open again the fields popup and see the value displayed in the popup 

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/oLIrYv

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment] 2024-01-04 14:27
@girishpanchal30 Tested and the issue is fixed now, thank you 👍

**Closed** 2024-02-28 17:52 UTC
Labels: bug, customer report
